---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-19 18:42
---

--- error抛出异常
--- pcall捕获异常

print(debug.traceback()) --打印堆栈
print("----------")

function err ()
    error("aaa")
end
if pcall(err) then--注意这里pcall的参数不带括号， 是函数的名字
    print("no error")
else
    print("have a error")
end

print("----------")

local sts, ero = pcall(function()--这里的变量名ero不能定义成error, 会跟error()冲突
    error({code=404})
end)
print(sts, ero.code)

print("----------")

--- pcall捕获异常
local sts, err = pcall(function()
    local ir = io.read("*number")
    if not ir then
        error({code = 404, msg = "invalid input"})
    end
end)
print(sts, err.code, err.msg)

print("----------")

--- xpcall捕获异常, 还可以传入一个函数. 出错的时候会调用这个函数(感觉他不会捕获error包装的异常，但是他会在error的时候，执行一个自定义的函数)
local sts, err = xpcall(function()
    local ir = io.read("*number")
    if not ir then
        error({code = 404, msg = "invalid input"})
    end
end, function ()
    print("eeeeeeeeee")
    print(debug.traceback())
end)
print(sts, err.code, err.msg)
